### ISSUE TITLE
Variable to control running barman tasks

### ISSUE THREAD

**Issue by jabbors** [giner/ansible-role-barman#4]
What do you think of adding a variable ie `barman_run_commands: true` to control whether or not to run the `ansible.builtin.command`s tasks part of configure.yaml?

In cases where the database is big (many terabytes) it will take a long time to complete the first backup and relying on the Ansible SSH connection to stay open the entire time is unlikely. In these cases it's preferable to start the initial backup manually.

If you like this idea I can contribute with a PR.

**Comment by jabbors** [comment]
Separate parameters would allow more control. I'll start working on a PR for this.

**Comment by giner** [comment]
Implemented with #7
