### ISSUE TITLE
Allow logging output from sensitive tasks

### ISSUE THREAD

**Issue by jabbors** [giner/ansible-role-barman#8]
What do you think of changing all `no_log: true` statements to `no_log: "{{ barman_configure_no_log }}"`?

This would allow the user to override the value when executing with `--extra-vars "barman_configure_no_log=false"`. I find this pattern useful in other modules when I perform a `--diff --check` to actually see what would change.

**Comment by giner** [comment]
This is a good idea actually. I'd go for `barman_no_log` for a simpler variable name.

**Comment by jabbors** [comment]
Great, I'll wrap up a PR with the simpler variable name.

**Comment by giner** [comment]
Implemented with #9
